### ISSUE TITLE
stack creation fails

### ISSUE THREAD

**Issue by marcusspitzmiller** [aws-quickstart/quickstart-sios-datakeeper#13]
Cannot use the cloudformation template, getting error creating WSFCNode2 and WSFCNode1 >> aPI: ec2:RunInstances Not authorized for images.

A search is suggesting that the cloudformation template is pointing to an outdated image.  

In us-west-2, the image is ami-956e7aec, which is from 2017.  There are newer images from 2018, but none of them are Pay as You Go windows 2016.  So I haven't been able to even update the cloudformation template manually with a new instance.

**Comment by carrollh** [comment]
We've already updated the AMI ids and the template, but there is an odd internal issue happening with the 2016 BYOL ami. We have a support ticket open with AWS already for that issue. In the meantime you can try out the develop branch as long as you don't select the BYOL 2016 AMI.

**Comment by Cavaci** [comment]
Hi Carrol.  I tried the template in the Develop branch and get the following error. I am trying to deploy in a new VPC. It got further but still fails. I am selecting the 2016 version of the O/S''s to make sure it's current and using the Pay as you go option. Any suggestions? using the Ohio region as well. Cheers. Dave 

CREATE_FAILED | AWS::CloudFormation::Stack | SIOSStack | Parameters: [OSVersion] do not exist in the template

Here is the summary of my deployment as well if this helps: 

Template
Template URL
https://s3.us-east-2.amazonaws.com/cf-templates-1vda293aahqgs-us-east-2/2018149rqZ-sios-datakeeper-master.templateh9nq7s91zwr
Description
This template deploys two Windows Server Failover Clustering (WSFC) nodes with SQL Server 2014 and DataKeeper replication software. This template also deploys the required AD architecture outlined in "Implementing Active Directory Domain Services in the AWS Cloud" **WARNING** This template creates Amazon EC2 Windows instance and related resources. You will be billed for the AWS resources used if you create a stack from this template.
Estimate cost
Cost
Details
Stack name:
SIOS-DATAKEEPER
Network Configuration

AvailabilityZones
us-east-2a,us-east-2b
VPCCIDR
10.0.0.0/16
PrivateSubnet1CIDR
10.0.0.0/19
PrivateSubnet2CIDR
10.0.32.0/19
PublicSubnet1CIDR
10.0.128.0/20
PublicSubnet2CIDR
10.0.144.0/20
Amazon EC2 Configuration

KeyPairName
sios-keypair
Microsoft Active Directory Configuration

ADServerOSVersion
2016
ADServer1InstanceType
t2.large
ADServer1NetBIOSName
DC1
ADServer1PrivateIP
10.0.0.10
ADServer2InstanceType
t2.large
ADServer2NetBIOSName
DC2
ADServer2PrivateIP
10.0.32.10
DomainDNSName
datakeeper.local
DomainNetBIOSName
DATAKEEPER
RestoreModePassword
·····
DomainAdminUser
siosadmin
DomainAdminPassword
·····
Remote Desktop Gateway Configuration

RDGWCIDR
10.0.128.0/20
RDGWInstanceType
t2.large
Replication Configuration

AMIType
PAYG
SIOSLicenseKeyFtpURL
SQLServerVersion
2014SP1
SQLServiceAccount
sqlsa
SQLServiceAccountPassword
·····
Volume1Size
100
Volume1Type
gp2
Volume1Iops
1000
Failover Cluster Configuration

ClusterNodeOSServerVersion
2016
WSFCNode1InstanceType
i3.xlarge
WSFCNode1NetBIOSName
WSFCNode1
WSFCNode1PrivateIP1
10.0.0.100
WSFCNode1PrivateIP2
10.0.0.101
WSFCNode1PrivateIP3
10.0.0.102
WSFCNode2InstanceType
i3.xlarge
WSFCNode2NetBIOSName
WSFCNode2
WSFCNode2PrivateIP1
10.0.32.100
WSFCNode2PrivateIP2
10.0.32.101
WSFCNode2PrivateIP3
10.0.32.102
AWS Quick Start Configuration

QSS3BucketName
aws-quickstart
QSS3KeyPrefix
quickstart-sios-datakeeper/

**Comment by carrollh** [comment]
It's the last two parameter values you used. You'll need to put the contents of the repo into an S3 bucket and folder of your own to get it to work. The bucket 'aws-quickstart' and folder 'quickstart-sios-datakeeper' are the ones that house the official master branch. So it's failing because the current official master template doesn't have some of the parameters you are specifying for the new sios-datakeeper template.

**Comment by Cavaci** [comment]
That makes sense. Thank you!  I will adjust and try again. cheers

**Comment by Cavaci** [comment]
I got the paths sorted out and the missing components from the DEV script but keeps hanging on the the domain wait condition. it looks like one AD controller is created then stalls.. and rolls back.. I tried different combinations of the O/S all as pay as you go with no luck. I am installing into a new VPC in US-East-2. not sure if that affects anything. I'm subscribed to the SIOS AMI.. wondering if anyone has had luck getting this running. next, going to turn off rollback and see where it lands and try and fix from there... 

Embedded stack arn:aws:cloudformation:us-east-2:095735628447:stack/sios-datakeeper-ADStack-5RIQCSPWMU95/41e5f040-6436-11e8-a4aa-50a68a1b16c6 was not successfully created: The following resource(s) failed to create: [DomainController1WaitCondition].

**Comment by carrollh** [comment]
That error doesn't mean much by itself. Maybe you're running into a ec2 resource limit. Check to make sure you're not exceeding the allowed number of cpus, public elastic ip adresses, etc. 
The only other thing that I can think of is that the submodule for the AD stack isn't up to date, but that's more of a hunch than from the error message. When you originally cloned the repo did you use the --recursive flag? (i.e. "git clone --recursive git@github.com:aws-quickstart/quickstart-sios-datakeeper.git"). You'll also need to switch to the develop branch using git. Both of those need to happen before you upload it to your own s3 bucket + folder.

**Comment by davmayd** [comment]
This is a stale issue, the templates have been updated
